#INCLUDE "EJ5.H"

VOID FICHEROMAYUSCULA(CHAR *FICHERO){
	FILE *FICH_ENTRADA;
	FILE *FICH_MAYUSCULA;

	CHAR NOMBRE[256]="MAYUSCULA-";
	STRCAT(NOMBRE,FICHERO);

	FICH_ENTRADA=FOPEN(FICHERO,"R");
	IF (FICH_ENTRADA==NULL){
		PRINTF("ERROR AL ABRIR EL FICHERO <%S>\N",FICHERO);
	}

	FICH_MAYUSCULA=FOPEN(NOMBRE,"W");
	IF (FICH_ENTRADA==NULL){
		PRINTF("ERROR AL ABRIR EL FICHERO <%S>\N",NOMBRE);
	}


	CHAR AUX,LETRA;

	AUX=FGETC(FICH_ENTRADA);

	WHILE(AUX!=EOF){
		LETRA=TOUPPER(AUX);
		FPUTC(LETRA,FICH_MAYUSCULA);
		AUX=FGETC(FICH_ENTRADA);
	}

	FCLOSE(FICH_ENTRADA);
	FCLOSE(FICH_MAYUSCULA);
}